name: Docker Build
on: [ push, pull_request ]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0
      - uses: actions/checkout@v2.4.0
      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2.7.0
        with:
          tags: test-build:latest
