name: Docker Build
on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.1.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.4.0
      - uses: actions/checkout@v4
      - name: Build
        id: docker_build
        uses: docker/build-push-action@v6.3.0
        with:
          tags: test-build:latest
