name: Docker Build
on: [ push, pull_request ]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.0.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1
      - uses: actions/checkout@v3
      - name: Build
        id: docker_build
        uses: docker/build-push-action@v3.1.1
        with:
          tags: test-build:latest
